### ISSUE TITLE
Explain @override

### ISSUE THREAD

**Issue by KISLAYA-SRI** [KISLAYA-SRI/THE-METRO-APP#13]
Explain why **@override** is used at line number 162 of Main.java
And what would happen if we remove this line.

`@Override
public int compareTo(DijkstraPair o) 
{
	return o.cost - this.cost;
}`

**Comment by anushkasinghal11** [comment]
I am interested to work on this issue.

**Comment by KISLAYA-SRI** [comment]
Assigned...
